author: Kathrin Gruber
markdown: kramdown
title: Introduction to R
description: Programming with R for FAECTOR
theme: minima
permalink: /:categories/

header_pages:
  - index.md
  - L1_A_Primer_on_R.md
  - Base_R.md
  - Data_import.md
  - L7_Programming_Functions.md
  - L7_Programming_Loops.md
  - L7_Programming_Tips.md
  - Grammer_of_Graphics.md
  - RMarkdown.md
